---

# playbook for digital ocean
- hosts: localhost
  connection: local

  tasks:
    - set_fact:
        _bw_cmd: "project_create"
      when: (do_project_id|length == 0) and (bw_cmd == "create")
  
    - name: Include Project Creation
      include_tasks: include_tasks/do_projects.yml
      when: (do_project_id|length == 0) and (bw_cmd == "create")
  
    - name: Include DO droplet creation
      include_tasks: include_tasks/do_droplet_creation.yml
      when: (bw_cmd is defined) and (bw_cmd == "create")
    
    - debug:
        msg: "Id: {{ droplet_id }} IP Address: {{ ip_address }}"
      when: (droplet_id is defined) and (ip_address is defined)
   
    - name: Include Resource Assign
      include_tasks: include_tasks/do_projects.yml
      vars:
        _bw_cmd: project_resource_assign
        _do_project_id: "{{ do_project_id }}"
      when: (droplet_id is defined) and (do_project_id|length > 0) and (bw_cmd == "create")
      
    - name: Delete DO droplet
      digital_ocean_droplet:
        state: absent
        name: "{{ do_instance_name }}"
        oauth_token: "{{ do_token }}"
        wait_timeout: 500
      when: (bw_cmd is defined) and (bw_cmd == "delete")