---

# playbook for digital ocean
- hosts: localhost
  connection: local

  tasks:
    - set_fact:
        _bw_cmd: "create_project"
      when: (do_project_id|length == 0) and (bw_cmd == "create_droplet")
  
    - name: Include Project Creation
      include_tasks: include_tasks/do_projects.yml
      when: (do_project_id|length == 0) and (bw_cmd == "create_droplet")
  
    - name: Include DO droplet creation
      include_tasks: include_tasks/do_droplet_creation.yml
      when: (bw_cmd is defined) and (bw_cmd == "create_droplet")
    
    - debug:
        msg: "Id: {{ droplet_id }} IP Address: {{ ip_address }}"
      when: (droplet_id is defined) and (ip_address is defined)
   
    - name: Include Resource Assign
      include_tasks: include_tasks/do_projects.yml
      vars:
        _bw_cmd: assign_project_resource
        _do_project_id: "{{ do_project_id }}"
      when: (droplet_id is defined) and (do_project_id|length > 0) and (bw_cmd == "create_droplet")
      
    - name: Delete DO droplet
      include_tasks: include_tasks/do_droplet_delete.yml
      when: (bw_cmd is defined) and (bw_cmd == "delete_droplet")
      
    - name: Reboot DO droplet
      include_tasks: include_tasks/do_droplet_actions.yml
      when: (bw_cmd is defined) and (bw_cmd == "reboot_droplet" or bw_cmd == "reset_droplet" or bw_cmd == "resize_droplet" or bw_cmd == "rebuild_droplet")