---

# playbook for digital ocean
- hosts: localhost
  connection: local

  tasks:
    - name: Include Project Creation
      include_tasks: include_tasks/do_projects.yml
      when: (do_project_id|length == 0)
  
    - name: Include DO droplet creation
      include_tasks: include_tasks/do_droplet_creation.yml
      register: _do_droplet_creation_result
      when: (bw_cmd is defined) and (bw_cmd == "create")
   