---

# playbook for digital ocean
- hosts: localhost
  connection: local
  vars_files:
    - defaults/main.yml  

  tasks:
    - set_fact:
        _bw_do_cmd: "create_project"
      when: (do_project_id|length <= 0) and (bw_do_cmd is defined) and (bw_do_cmd == "create_droplet") and (do_project_name|length > 0)
  
    - name: Include Project Creation
      include_tasks: tasks/do_projects.yml
      when: (do_project_id|length <= 0) and (bw_do_cmd is defined)  and (bw_do_cmd == "create_droplet") and (do_project_name|length > 0)
  
    - name: Include DO droplet creation
      include_tasks: tasks/do_droplet_creation.yml
      when: (bw_do_cmd is defined) and (bw_do_cmd is defined)  and (bw_do_cmd == "create_droplet") and (do_instance_name|length > 0)
    
    - debug:
        msg: "Id: {{ droplet_id }} IP Address: {{ ip_address }}"
      when: (droplet_id is defined) and (ip_address is defined)
                    
    - name: Include Resource Assign
      include_tasks: tasks/do_projects.yml
      vars:
        _bw_do_cmd: assign_project_resource
        _do_project_id: "{{ do_project_id }}"
      when: (droplet_id is defined) and (do_project_id|length > 0) and (bw_do_cmd is defined)  and (bw_do_cmd == "create_droplet")
      
    - name: Delete DO droplet
      include_tasks: tasks/do_droplet_delete.yml
      when: (bw_do_cmd is defined) and (bw_do_cmd == "delete_droplet")
      
    - name: DO droplet actions
      include_tasks: tasks/do_droplet_actions.yml
      when: (bw_do_cmd is defined) and (bw_do_cmd == "reboot_droplet" or bw_do_cmd == "reset_droplet" or bw_do_cmd == "resize_droplet" or bw_do_cmd == "rebuild_droplet" or bw_do_cmd == "suspend_droplet" or bw_do_cmd == "unsuspend_droplet") 
      
    - name: DO Block Storage
      include_tasks: tasks/do_block.yml
      when: (bw_do_cmd is defined) and (bw_do_cmd == "create_volume" or bw_do_cmd == "create_attach_volume" or bw_do_cmd == "attach_volume" or bw_do_cmd == "delete_volume" or bw_do_cmd == "detach_volume" or bw_do_cmd == "resize_volume")
                 
    - name: Waiting for Droplet to start
      pause:
        seconds: 30
      when: (bw_do_cmd is defined) and (bw_do_cmd == "create_droplet")
      
    - name: Set Stats for Workflow
      set_stats:
        data:
          vmid: "{{ droplet_id }}"
      when: (droplet_id is defined)
  
    - name: Add Host
      import_role:
        name: anoop.awx
      vars:
        bw_awx_inventory_id: "{{ inventory_id }}"
        bw_awx_admin_password: spiderMan05
      when: "(ip_address is defined)"  
      
  # Setting Json Data to post to BW Response
    - name: set variable for create account
      set_fact:
        _result: "{\"ansible_data\": {\"vmid\":\"{{ vmid | default(\"\")}}\",\"ipaddress\":\"{{ ip_address | default(\"\") }}\"}"
      when: (bw_do_cmd == "create_droplet") and (bw_custom_data|length > 0)
             
    - name: set variable for create volume
      set_fact:
        _result: "{\"ansible_data\": {\"volumeid\":\"{{ _do_volume_id }}\"}"
      when: (bw_do_cmd == "create_volume") and (bw_custom_data|length > 0) and (_do_volume_id is defined)

    - name: Response back to BW
      import_role:
        name: anoop.bwresponse
      vars:
        bw_response_body: "{{ _result }}"
      when: (_result is defined) and (bw_do_cmd == "create_droplet") and (bw_custom_data|length > 0)          