---

- name: save host
  uri:
    url: "http://10.10.0.4/api/v2/inventories/{{ inventory_id }}/hosts/"
    user: "admin"
    password: "spiderMan05"
    method: POST
    validate_certs: false
    return_content: yes
    force_basic_auth: yes
    status_code: 201
    headers:
      Accept: "application/json"
    body_format: json
    body: "{\"inventory\": {{ inventory_id }},\"name\":\"{{ ip_address }}\", \"variables\": \"ansible_port: 22\\nansible_user: root\\nansible_become: yes\"}"
  ignore_errors: yes 
  when: (ip_address is defined)
  
- name: Set Stats for Workflow
  set_stats:
    data:
      ip_address: "{{ ip_address }}"
  when: (ip_address is defined)