---

- name: Including Variable
  include_vars: vars/main.yml

- name: Delete Droplet
  uri:
    url: "{{ url }}/{{ version }}/droplets/{{do_instance_name}}"
    method: DELETE
    validate_certs: false
    return_content: yes
    status_code: 204
    headers:
      Accept: "application/json"
      Authorization: "Bearer {{ do_token }}"
  ignore_errors: yes
  when: (bw_do_cmd == "delete_droplet")