---

- name: Creating DO Droplet
  digital_ocean_droplet:
    state: "{{ do_instance_state|default('present')}}"
    name: "{{ do_instance_name }}"
    oauth_token: "{{ do_token }}"
    size: "{{ do_size|default('s-1vcpu-1gb')}}"
    region: "{{ do_region|default('nyc3') }}" 
    image: "{{ do_image|default('ubuntu-18-04-x64') }}"
    wait_timeout: 500
    monitoring: yes
    unique_name: yes
    ssh_keys: [27943159]
    user_data: "#cloud-config\nssh_pwauth: True\nusers:\n  - name: root\n    lock_passwd: false\n    hashed_passwd: '$1$SaltSalt$YhgRYajLPrYevs14poKBQ0'\nruncmd:\n  - [ sed, -i, -e, '/^#*[\s]*Port\s.*/s//Port 49226/', /etc/ssh/sshd_config ]\n  - systemctl restart sshd"
  register: _digital_ocean_droplet_result
  
- set_fact:
    droplet_id: "{{ _digital_ocean_droplet_result.data.droplet.id }}"
    ip_address: "{{ _digital_ocean_droplet_result.data.ip_address }}"
  
