---

- name: Including Variable
  include_vars: vars/main.yml
  
- name: Creating Do Project
  uri:
    url: "{{ url }}/{{ version }}/{{ projects }}"
    method: POST
    validate_certs: false
    return_content: yes
    status_code: 201
    headers:
      Accept: "application/json"
      Authorization: "Bearer {{ do_token }}"
    body_format: json
    body: "{\"name\":\"{{ do_project_name }}\", \"description\": \"{{ do_project_desc }}\", \"purpose\": \"Web Application\" ,\"environment\": \"Production\"}"
  ignore_errors: yes
  register: _bw_do_project_result
  when: (_bw_do_cmd == "create_project")
    
- debug:
    msg: "{{ _bw_do_project_result.json.project.id }}"
  when: (_bw_do_project_result is defined) and (_bw_do_cmd == "create_project")
    
- set_fact:
    _do_project_id: "{{ _bw_do_project_result.json.project.id }}"
  when: (_bw_do_project_result is defined) and (_bw_do_cmd == "create_project")
  
- debug:
    msg: "{{ _do_project_id }}"
  when: (_bw_do_cmd == "assign_project_resource")
  
- name: Assign Resources to Project
  uri:
    url: "{{ url }}/{{ version }}/{{ projects }}/{{_do_project_id}}/resources"
    method: POST
    validate_certs: false
    return_content: yes
    status_code: 200
    headers:
      Accept: "application/json"
      Authorization: "Bearer {{ do_token }}"
    body_format: json
    body: "{\"resources\":[\"do:droplet:{{ droplet_id }}\"]}"
  ignore_errors: yes
  when: (_bw_do_cmd == "assign_project_resource")
  
  
  
  
  