---

- name: Including Variable
  include_vars: vars/main.yml
  
- name: Creating DO SSH Key
  uri:
    url: "{{ url }}/{{ version }}/account/keys"
    method: POST
    validate_certs: false
    return_content: yes
    status_code: 201
    headers:
      Accept: "application/json"
      Authorization: "Bearer {{ do_token }}"
    body_format: json
    body: "{\"name\":\"{{ do_project_name }}\", \"public_key\": \"{{ do_public_key }}\""
  ignore_errors: yes
  register: _bw_do_sshkey_result
  when: (_bw_cmd == "sshkey_create" and do_public_key is defined and do_public_key|length > 0)
    
- debug:
    msg: "{{ _bw_do_sshkey_result }}"
  when: (_bw_do_sshkey_result is defined)
    
  
  